name: Build and Release Curriculum PDFs

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache TeXLive dependencies
        id: cache-texlive
        uses: actions/cache@v4
        with:
          path: /usr/share/texlive
          key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}

      - name: Install TeXLive dependencies
        if: steps.cache-texlive.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-extra

      - name: Build PDFs
        run: make all

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload PDFs to Release
        id: upload-assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            curriculum.pdf
            curriculum-pt.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
